import * as Cesium from "cesium";
export default class PlotRectangleDrawer {
    viewer: any;
    scene: any;
    clock: any;
    canvas: any;
    camera: any;
    ellipsoid: any;
    tooltip: any;
    entity: any;
    positions: any;
    drawHandler: any;
    modifyHandler: any;
    okHandler: any;
    cancelHandler: any;
    dragIconLight: string;
    material: any;
    outlineMaterial: any;
    fill: boolean;
    outline: boolean;
    outlineWidth: number;
    extrudedHeight: number;
    toolBarIndex: any;
    layerId: string;
    params: any;
    ground: boolean;
    shapeColor: any;
    outlineColor: any;
    shapeName: any;
    isClickConfirm: boolean;
    constructor(viewer: any);
    clear(): void;
    clear2(): void;
    showModifyRectangle(options: any): Promise<unknown>;
    startDrawRectangle(options: any): Promise<unknown>;
    _startModify(): void;
    _createPoint(cartesian: any, oid: any): any;
    _showRegion2Map(): void;
    _showModifyRegion2Map(): void;
    _computeRectangle(p1: any, p2: any): Cesium.Rectangle;
    createToolBar(): Promise<void>;
    _isSimpleXYZ(p1: any, p2: any): boolean;
    _clearMarkers(layerName: string): void;
}
